# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_test_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Test_Post',
        ),
    ]
